name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        NODE_ENV: local
        PORT: 3004
        HOST: 0.0.0.0
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
